### PR TITLE
feat : implement community create node (#community,#user)

### PR DESCRIPTION
**Pull request by ghost**
+ models/groupdetail.js -> community info in user model
* models/* -> change to save more detail information
* routes/coms/apiResponse.js -> solve includes function error of
undefined obj
+ routes/coms/genPrivilege -> build privilege object and publish to db
+ routes/coms/updateUserList -> build & update userlist and return
+ routes/group/create.js -> community create apinode for user
* routes/swagger.yaml -> update api document file

[ToDo] save community information to user field.

### CODE REVIEW

**Comment by YunYeongChang** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- routes/group/updateUserlist.js  8
- routes/group/genPrivilege.js  6
- routes/coms/apiResponse.js  9
- routes/group/create.js  12
         

Clones added
============
- models/group/grouplog.js  1
- routes/group/create.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/implude/local-community-backend/pullRequest?prid=6369326&bid=20668314)

**Comment by YunYeongChang** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- routes/coms/apiResponse.js  9
- routes/group/genPrivilege.js  6
- routes/group/updateGrouplist.js  10
- routes/group/create.js  13
- routes/group/updateUserlist.js  8
         

Clones added
============
- routes/group/create.js  2
- models/group/grouplog.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/implude/local-community-backend/pullRequest?prid=6369326&bid=20668314)

**Comment by YunYeongChang** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- routes/group/updateGrouplist.js  10
- routes/coms/apiResponse.js  9
- routes/group/genPrivilege.js  6
- routes/group/create.js  13
- routes/group/updateUserlist.js  8
         

Clones added
============
- routes/group/create.js  2
- models/group/grouplog.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/implude/local-community-backend/pullRequest?prid=6369326&bid=20668314)

**Review by alsh02 — APPROVED** [review]
unbelievable perfect

**Pull request merged**
